#!/bin/bash

gcc main.c -o main -ldl -Wall
gcc portapotty.c -o override/libexamplefn.so -fPIC -shared -ldl -D_GNU_SOURCE -Wall
gcc example.c -o libexamplefn.so -fPIC -shared -ldl -D_GNU_SOURCE -Wall

sudo ln -sf "$(pwd)/libexamplefn.so" /usr/lib/libexamplefn.so

./main
echo

echo "Doesn't..."
LD_LIBRARY_PATH="$(pwd)/override/" ./main
echo

echo "Works..."
LD_LIBRARY_PATH="$(pwd)/override/" LD_PRELOAD="/usr/lib/libexamplefn.so" ./main

