#!/bin/bash

mkdir -p override

gcc example.c -o libexamplefn.so -fPIC -shared -ldl -D_GNU_SOURCE -Wall
sudo ln -sf "$(pwd)/libexamplefn.so" /usr/lib/libexamplefn.so

gcc main.c -o main1 -ldl -Wall -lexamplefn
gcc main.c -o main2 -ldl -Wall -DDLSYM_LIBEXAMPLEFN

gcc example-stub.c -o override/libexamplefn-stub.so -fPIC -shared -Wall
gcc portapotty.c -o override/libexamplefn.so -fPIC -shared -ldl -D_GNU_SOURCE -Wall -lexamplefn-stub -Loverride

rm override/libexamplefn-stub.so
ln -sf "/lib/libexamplefn.so" "override/libexamplefn-stub.so"

LD_LIBRARY_PATH="$(pwd)/override/" ./main1
LD_LIBRARY_PATH="$(pwd)/override/" ./main2
